[package]
name = "ec"
version = "0.1.0"
edition = "2024"

[dependencies]
bitarray = {git = "https://github.com/MarcusTL12/bitarray_rs"}
home = "0.5"
itertools = "0.14"
ndarray = "0.17"
num-rational = "0.4"
rayon = "1.11"
regex = "1.12"
